### PR TITLE
snap package

### PR DESCRIPTION
**Pull request by mikeroyal**
Includes snapcraft.yaml file

### CODE REVIEW

**Comment by bradrydzewski** [comment]
this looks good to me ... any good resources for how and where to publish snaps?  I am familiar with snaps, but haven't used them yet. So interested in learning more.

**Comment by mikeroyal** [comment]
Hi @bradrydzewski, it's a pretty easy process to publish here's the link to follow. https://docs.snapcraft.io/releasing-your-app/6795

**Comment by Lin-Buo-Ren** [comment]
I'm also looking forward for this as well as I'm not (quite) willing to manually applying updates to Go binaries once in a while and snap's automatic update and CLI-friendly nature makes it ideal for drone-cli.

I've helped several projects adopting snaps, feel free to ask any questions to moving things forward.

**Comment by tphoney** [comment]
This looks good 🥇
we have created a proposal drone/proposal#4 to gauge support for this feature, as we would need to setup the infrastructure / support for maintaining this going forward. If you want it give it a 👍

**Pull request closed without merging**
